/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 30 17:46:22 GMT 2016
 */

package nul.study.videostore.EvoSuiteTests;

import org.junit.Test;
import static org.junit.Assert.*;

import java.lang.annotation.Annotation;

import nul.study.videostore.ChildrensMovie;
import nul.study.videostore.Customer;
import nul.study.videostore.Movie;
import nul.study.videostore.NewReleaseMovie;
import nul.study.videostore.RegularMovie;
import nul.study.videostore.Rental;

public class Customer_ESTest {
	
	public static void assertThrownBy(String sourceClass, Throwable t) throws AssertionError{
        StackTraceElement[] stackTrace = t.getStackTrace();

        // TODO: Force mocked exceptions to always have stack trace
        if(stackTrace.length == 0)
            return;

        StackTraceElement el = stackTrace[0];

        if(sourceClass==null){
            return; //can this even happen?
        }


        String name = el.getClassName();
        if(sourceClass.equals(name)){
            return;
        }
 
        Class<?> klass;

        try {
           klass = Customer_ESTest.class.getClassLoader().loadClass(sourceClass);
        } catch (ClassNotFoundException e) {
            throw new AssertionError("Cannot load/analyze class "+sourceClass);
        }

        for(Annotation annotation : klass.getAnnotations()){
            if(annotation.getClass().getName().equals(name)){
                return;
            }
        }

        while(klass != null){
            klass = klass.getSuperclass();
            if(klass != null && klass.getName().equals(name)){
                return;
            }
        }

        throw new AssertionError("Exception was not thrown in "+sourceClass +" but in "+el+": "+t);
    }

	
	
  //Test case number: 0
  /*
   * 124 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - true
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - true
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false
   * Goal 11. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false
   * Goal 12. nul.study.videostore.Customer.statement()Ljava/lang/String;: I60 Branch 6 IF_ICMPLE L33 - true
   * Goal 13. nul.study.videostore.Customer.statement()Ljava/lang/String;: I98 Branch 7 IF_ICMPLE L41 - false
   * Goal 14. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true
   * Goal 15. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 16. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 21. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 22. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 23. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 24. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 25. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I60 Branch 6 IF_ICMPLE L33 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 26. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I98 Branch 7 IF_ICMPLE L41 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 27. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 28. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 29. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 30. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 31. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 32. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 33. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 34. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 43. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 32
   * Goal 44. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 33
   * Goal 45. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 40
   * Goal 46. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 41
   * Goal 47. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 42
   * Goal 48. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 49. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 50. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 51. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 52. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 53. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 54. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 55. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 56. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 57. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 58. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 59. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 60. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 61. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 62. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 63. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 64. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 65. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 66. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 67. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 68. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 69. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   * Goal 70. Weak Mutation 9: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - InsertUnaryOp Negation of thisAmount
   * Goal 71. Weak Mutation 10: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 0.0
   * Goal 72. Weak Mutation 11: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 1.0
   * Goal 73. Weak Mutation 12: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> -1.0
   * Goal 74. Weak Mutation 13: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 3.0
   * Goal 75. Weak Mutation 14: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> %
   * Goal 76. Weak Mutation 15: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> -
   * Goal 77. Weak Mutation 16: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> *
   * Goal 78. Weak Mutation 17: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> /
   * Goal 79. Weak Mutation 18: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 0
   * Goal 80. Weak Mutation 19: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 1
   * Goal 81. Weak Mutation 20: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> -1
   * Goal 82. Weak Mutation 21: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 3
   * Goal 83. Weak Mutation 24: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceComparisonOperator <= -> ==
   * Goal 84. Weak Mutation 63: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceVariable thisAmount -> totalAmount
   * Goal 85. Weak Mutation 64: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - InsertUnaryOp Negation of thisAmount
   * Goal 86. Weak Mutation 65: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 0.0
   * Goal 87. Weak Mutation 66: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 1.0
   * Goal 88. Weak Mutation 67: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> -1.0
   * Goal 89. Weak Mutation 68: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 0.5
   * Goal 90. Weak Mutation 69: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 2.5
   * Goal 91. Weak Mutation 70: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> %
   * Goal 92. Weak Mutation 71: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> -
   * Goal 93. Weak Mutation 72: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> *
   * Goal 94. Weak Mutation 73: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> /
   * Goal 95. Weak Mutation 74: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 0
   * Goal 96. Weak Mutation 75: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 1
   * Goal 97. Weak Mutation 76: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> -1
   * Goal 98. Weak Mutation 77: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 2
   * Goal 99. Weak Mutation 78: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 4
   * Goal 100. Weak Mutation 79: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceComparisonOperator <= -> -1
   * Goal 101. Weak Mutation 82: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceVariable thisAmount -> totalAmount
   * Goal 102. Weak Mutation 83: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - InsertUnaryOp Negation of thisAmount
   * Goal 103. Weak Mutation 84: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 3 -> 0
   * Goal 104. Weak Mutation 85: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 3 -> 1
   * Goal 105. Weak Mutation 86: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 3 -> -1
   * Goal 106. Weak Mutation 87: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 3 -> 2
   * Goal 107. Weak Mutation 88: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 3 -> 4
   * Goal 108. Weak Mutation 89: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator - -> +
   * Goal 109. Weak Mutation 90: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator - -> %
   * Goal 110. Weak Mutation 91: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator - -> *
   * Goal 111. Weak Mutation 92: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator - -> /
   * Goal 112. Weak Mutation 93: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 1.5 -> 0.0
   * Goal 113. Weak Mutation 94: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 1.5 -> 1.0
   * Goal 114. Weak Mutation 95: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 1.5 -> -1.0
   * Goal 115. Weak Mutation 96: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 1.5 -> 0.5
   * Goal 116. Weak Mutation 97: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceConstant - 1.5 -> 2.5
   * Goal 117. Weak Mutation 98: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator * -> +
   * Goal 118. Weak Mutation 99: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator * -> %
   * Goal 119. Weak Mutation 100: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator * -> -
   * Goal 120. Weak Mutation 101: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator * -> /
   * Goal 121. Weak Mutation 102: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator + -> %
   * Goal 122. Weak Mutation 103: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator + -> -
   * Goal 123. Weak Mutation 104: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator + -> *
   * Goal 124. Weak Mutation 105: nul.study.videostore.Customer.statement()Ljava/lang/String;:42 - ReplaceArithmeticOperator + -> /
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Customer customer0 = new Customer("You-owe ");
      RegularMovie regularMovie0 = new RegularMovie("You-owe ");
      Rental rental0 = new Rental(regularMovie0, 1);
      customer0.addRental(rental0);
      ChildrensMovie childrensMovie0 = new ChildrensMovie("You-owe ");
      Rental rental1 = new Rental(childrensMovie0, 362);
      customer0.addRental(rental1);
      String string0 = customer0.statement();
      assertEquals("Rental Record for You-owe \n\tYou-owe \t2.0\n\tYou-owe \t540.0\nYou owed 542.0\nYou earned 2 frequent renter points\n", string0);
  }

  //Test case number: 1
  /*
   * 75 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - true
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - false
   * Goal 11. nul.study.videostore.Customer.statement()Ljava/lang/String;: I124 Branch 9 IF_ICMPLE L48 - true
   * Goal 12. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 13. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 14. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 15. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 16. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I124 Branch 9 IF_ICMPLE L48 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 21. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 22. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 23. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 24. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 25. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 26. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 27. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 28. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 29. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 30. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 31. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 32. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 33. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 34. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 37
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 38
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 43. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 44. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 45. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 46. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 47. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 48. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 49. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 50. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 51. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 52. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 53. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 54. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 55. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 56. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 57. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 58. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 59. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 60. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   * Goal 61. Weak Mutation 48: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceVariable thisAmount -> totalAmount
   * Goal 62. Weak Mutation 49: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - InsertUnaryOp Negation of thisAmount
   * Goal 63. Weak Mutation 50: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 0
   * Goal 64. Weak Mutation 51: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 1
   * Goal 65. Weak Mutation 52: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> -1
   * Goal 66. Weak Mutation 53: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 2
   * Goal 67. Weak Mutation 54: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 4
   * Goal 68. Weak Mutation 55: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> +
   * Goal 69. Weak Mutation 56: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> %
   * Goal 70. Weak Mutation 57: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> -
   * Goal 71. Weak Mutation 58: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> /
   * Goal 72. Weak Mutation 59: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> %
   * Goal 73. Weak Mutation 60: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> -
   * Goal 74. Weak Mutation 61: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> *
   * Goal 75. Weak Mutation 62: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> /
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Customer customer0 = new Customer("Hu,x&G271\"7:Ir");
      NewReleaseMovie newReleaseMovie0 = new NewReleaseMovie("Hu,x&G271\"7:Ir");
      Rental rental0 = new Rental(newReleaseMovie0, (-1));
      customer0.addRental(rental0);
      customer0.addRental(rental0);
      String string0 = customer0.statement();
      assertEquals("Rental Record for Hu,x&G271\"7:Ir\n\tHu,x&G271\"7:Ir\t-3.0\n\tHu,x&G271\"7:Ir\t-3.0\nYou owed -6.0\nYou earned 2 frequent renter points\n", string0);
  }

  //Test case number: 2
  /*
   * 99 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - true
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - true
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false
   * Goal 11. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false
   * Goal 12. nul.study.videostore.Customer.statement()Ljava/lang/String;: I60 Branch 6 IF_ICMPLE L33 - true
   * Goal 13. nul.study.videostore.Customer.statement()Ljava/lang/String;: I98 Branch 7 IF_ICMPLE L41 - true
   * Goal 14. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true
   * Goal 15. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 16. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 21. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 22. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 23. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 24. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 25. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I60 Branch 6 IF_ICMPLE L33 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 26. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I98 Branch 7 IF_ICMPLE L41 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 27. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 28. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 29. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 30. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 31. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 32. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 33. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 34. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 43. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 32
   * Goal 44. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 33
   * Goal 45. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 40
   * Goal 46. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 41
   * Goal 47. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 48. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 49. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 50. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 51. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 52. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 53. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 54. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 55. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 56. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 57. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 58. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 59. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 60. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 61. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 62. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 63. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 64. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 65. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 66. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 67. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 68. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   * Goal 69. Weak Mutation 8: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceVariable thisAmount -> totalAmount
   * Goal 70. Weak Mutation 9: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - InsertUnaryOp Negation of thisAmount
   * Goal 71. Weak Mutation 10: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 0.0
   * Goal 72. Weak Mutation 11: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 1.0
   * Goal 73. Weak Mutation 12: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> -1.0
   * Goal 74. Weak Mutation 13: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 3.0
   * Goal 75. Weak Mutation 14: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> %
   * Goal 76. Weak Mutation 15: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> -
   * Goal 77. Weak Mutation 16: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> *
   * Goal 78. Weak Mutation 17: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> /
   * Goal 79. Weak Mutation 18: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 0
   * Goal 80. Weak Mutation 19: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 1
   * Goal 81. Weak Mutation 20: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> -1
   * Goal 82. Weak Mutation 21: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 3
   * Goal 83. Weak Mutation 23: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceComparisonOperator <= -> <
   * Goal 84. Weak Mutation 64: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - InsertUnaryOp Negation of thisAmount
   * Goal 85. Weak Mutation 65: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 0.0
   * Goal 86. Weak Mutation 66: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 1.0
   * Goal 87. Weak Mutation 67: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> -1.0
   * Goal 88. Weak Mutation 68: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 0.5
   * Goal 89. Weak Mutation 69: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 2.5
   * Goal 90. Weak Mutation 70: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> %
   * Goal 91. Weak Mutation 71: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> -
   * Goal 92. Weak Mutation 72: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> *
   * Goal 93. Weak Mutation 73: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> /
   * Goal 94. Weak Mutation 74: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 0
   * Goal 95. Weak Mutation 75: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 1
   * Goal 96. Weak Mutation 76: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> -1
   * Goal 97. Weak Mutation 77: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 2
   * Goal 98. Weak Mutation 78: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 4
   * Goal 99. Weak Mutation 81: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceComparisonOperator <= -> ==
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Customer customer0 = new Customer((String) null);
      RegularMovie regularMovie0 = new RegularMovie((String) null);
      ChildrensMovie childrensMovie0 = new ChildrensMovie((String) null);
      Rental rental0 = new Rental(childrensMovie0, 0);
      customer0.addRental(rental0);
      Rental rental1 = new Rental(regularMovie0, 2);
      customer0.addRental(rental1);
      String string0 = customer0.statement();
      assertEquals("Rental Record for null\n\tnull\t1.5\n\tnull\t2.0\nYou owed 3.5\nYou earned 2 frequent renter points\n", string0);
  }

  //Test case number: 3
  /*
   * 13 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 3. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 4. Branch nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch in context: nul.study.videostore.Customer:getName()Ljava/lang/String;
   * Goal 5. [Output]: nul.study.videostore.Customer.getName()Ljava/lang/String;:Null
   * Goal 6. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 7. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 8. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 9. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 10. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 11. [METHOD] nul.study.videostore.Customer.getName()Ljava/lang/String;
   * Goal 12. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 13. [METHODNOEX] nul.study.videostore.Customer.getName()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Customer customer0 = new Customer((String) null);
      String string0 = customer0.getName();
      assertNull(string0);
  }

  //Test case number: 4
  /*
   * 13 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 3. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 4. Branch nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch in context: nul.study.videostore.Customer:getName()Ljava/lang/String;
   * Goal 5. [Output]: nul.study.videostore.Customer.getName()Ljava/lang/String;:EmptyString
   * Goal 6. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 7. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 8. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 9. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 10. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 11. [METHOD] nul.study.videostore.Customer.getName()Ljava/lang/String;
   * Goal 12. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 13. [METHODNOEX] nul.study.videostore.Customer.getName()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Customer customer0 = new Customer("");
      String string0 = customer0.getName();
      assertEquals("", string0);
  }

  //Test case number: 5
  /*
   * 35 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 5. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 6. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 7. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 8. statement()Ljava/lang/String;_java.lang.NullPointerException_IMPLICIT
   * Goal 9. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 10. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 11. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 12. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 13. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 14. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 15. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 16. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 17. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 18. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 19. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 20. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 21. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 22. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 23. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 24. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 25. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 26. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 27. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 28. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 29. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 30. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 31. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 32. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 33. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 34. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 35. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Customer customer0 = new Customer((String) null);
      customer0.addRental((Rental) null);
      // Undeclared exception!
      try { 
        customer0.statement();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("nul.study.videostore.Customer", e);
      }
  }

  //Test case number: 6
  /*
   * 13 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 3. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 4. Branch nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch in context: nul.study.videostore.Customer:getName()Ljava/lang/String;
   * Goal 5. [Output]: nul.study.videostore.Customer.getName()Ljava/lang/String;:NonEmptyString
   * Goal 6. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 7. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 8. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 9. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 10. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 11. [METHOD] nul.study.videostore.Customer.getName()Ljava/lang/String;
   * Goal 12. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 13. [METHODNOEX] nul.study.videostore.Customer.getName()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Customer customer0 = new Customer("Hu,x&G271\"7:Ir");
      String string0 = customer0.getName();
      assertEquals("Hu,x&G271\"7:Ir", string0);
  }

  //Test case number: 7
  /*
   * 75 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - true
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - false
   * Goal 11. nul.study.videostore.Customer.statement()Ljava/lang/String;: I124 Branch 9 IF_ICMPLE L48 - false
   * Goal 12. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 13. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 14. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 15. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 16. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I124 Branch 9 IF_ICMPLE L48 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 21. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 22. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 23. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 24. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 25. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 26. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 27. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 28. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 29. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 30. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 31. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 32. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 33. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 34. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 37
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 38
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 49
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 43. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 44. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 45. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 46. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 47. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 48. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 49. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 50. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 51. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 52. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 53. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 54. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 55. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 56. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 57. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 58. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 59. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 60. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 61. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   * Goal 62. Weak Mutation 49: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - InsertUnaryOp Negation of thisAmount
   * Goal 63. Weak Mutation 50: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 0
   * Goal 64. Weak Mutation 51: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 1
   * Goal 65. Weak Mutation 52: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> -1
   * Goal 66. Weak Mutation 53: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 2
   * Goal 67. Weak Mutation 54: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceConstant - 3 -> 4
   * Goal 68. Weak Mutation 55: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> +
   * Goal 69. Weak Mutation 56: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> %
   * Goal 70. Weak Mutation 57: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> -
   * Goal 71. Weak Mutation 58: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator * -> /
   * Goal 72. Weak Mutation 59: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> %
   * Goal 73. Weak Mutation 60: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> -
   * Goal 74. Weak Mutation 61: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> *
   * Goal 75. Weak Mutation 62: nul.study.videostore.Customer.statement()Ljava/lang/String;:37 - ReplaceArithmeticOperator + -> /
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Customer customer0 = new Customer("j");
      NewReleaseMovie newReleaseMovie0 = new NewReleaseMovie("j");
      Rental rental0 = new Rental(newReleaseMovie0, 228);
      customer0.addRental(rental0);
      String string0 = customer0.statement();
      assertEquals("Rental Record for j\n\tj\t684.0\nYou owed 684.0\nYou earned 2 frequent renter points\n", string0);
  }

  //Test case number: 8
  /*
   * 98 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - true
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I60 Branch 6 IF_ICMPLE L33 - false
   * Goal 11. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true
   * Goal 12. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 13. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 14. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 15. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 16. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I60 Branch 6 IF_ICMPLE L33 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 21. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 22. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 23. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 24. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 25. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 26. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 27. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 28. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 29. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 30. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 31. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 32. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 33. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 34. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 32
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 33
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 34
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 43. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 44. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 45. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 46. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 47. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 48. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 49. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 50. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 51. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 52. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 53. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 54. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 55. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 56. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 57. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 58. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 59. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 60. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 61. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   * Goal 62. Weak Mutation 9: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - InsertUnaryOp Negation of thisAmount
   * Goal 63. Weak Mutation 10: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 0.0
   * Goal 64. Weak Mutation 11: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 1.0
   * Goal 65. Weak Mutation 12: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> -1.0
   * Goal 66. Weak Mutation 13: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceConstant - 2.0 -> 3.0
   * Goal 67. Weak Mutation 14: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> %
   * Goal 68. Weak Mutation 15: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> -
   * Goal 69. Weak Mutation 16: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> *
   * Goal 70. Weak Mutation 17: nul.study.videostore.Customer.statement()Ljava/lang/String;:32 - ReplaceArithmeticOperator + -> /
   * Goal 71. Weak Mutation 18: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 0
   * Goal 72. Weak Mutation 19: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 1
   * Goal 73. Weak Mutation 20: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> -1
   * Goal 74. Weak Mutation 21: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceConstant - 2 -> 3
   * Goal 75. Weak Mutation 22: nul.study.videostore.Customer.statement()Ljava/lang/String;:33 - ReplaceComparisonOperator <= -> -1
   * Goal 76. Weak Mutation 25: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceVariable thisAmount -> totalAmount
   * Goal 77. Weak Mutation 26: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - InsertUnaryOp Negation of thisAmount
   * Goal 78. Weak Mutation 27: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 2 -> 0
   * Goal 79. Weak Mutation 28: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 2 -> 1
   * Goal 80. Weak Mutation 29: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 2 -> -1
   * Goal 81. Weak Mutation 30: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 2 -> 3
   * Goal 82. Weak Mutation 31: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator - -> +
   * Goal 83. Weak Mutation 32: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator - -> %
   * Goal 84. Weak Mutation 33: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator - -> *
   * Goal 85. Weak Mutation 34: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator - -> /
   * Goal 86. Weak Mutation 35: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 1.5 -> 0.0
   * Goal 87. Weak Mutation 36: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 1.5 -> 1.0
   * Goal 88. Weak Mutation 37: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 1.5 -> -1.0
   * Goal 89. Weak Mutation 38: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 1.5 -> 0.5
   * Goal 90. Weak Mutation 39: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceConstant - 1.5 -> 2.5
   * Goal 91. Weak Mutation 40: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator * -> +
   * Goal 92. Weak Mutation 41: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator * -> %
   * Goal 93. Weak Mutation 42: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator * -> -
   * Goal 94. Weak Mutation 43: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator * -> /
   * Goal 95. Weak Mutation 44: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator + -> %
   * Goal 96. Weak Mutation 45: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator + -> -
   * Goal 97. Weak Mutation 46: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator + -> *
   * Goal 98. Weak Mutation 47: nul.study.videostore.Customer.statement()Ljava/lang/String;:34 - ReplaceArithmeticOperator + -> /
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Customer customer0 = new Customer((String) null);
      RegularMovie regularMovie0 = new RegularMovie((String) null);
      Rental rental0 = new Rental(regularMovie0, 9);
      customer0.addRental(rental0);
      String string0 = customer0.statement();
      assertEquals("Rental Record for null\n\tnull\t12.5\nYou owed 12.5\nYou earned 1 frequent renter points\n", string0);
  }

  //Test case number: 9
  /*
   * 56 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - true
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true
   * Goal 11. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 12. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 13. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 14. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 15. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 16. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 21. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 22. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 23. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 24. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 25. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 26. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 27. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 28. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 29. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 30. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 31. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 32. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 33. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 34. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 43. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 44. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 45. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 46. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 47. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 48. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 49. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 50. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 51. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 52. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 53. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 54. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 55. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 56. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Customer customer0 = new Customer("Rental Record for ");
      ChildrensMovie childrensMovie0 = new ChildrensMovie("Rental Record for Rental Record for \nYou owed 0.0\nYou earned 0 frequent renter points\n");
      childrensMovie0.setPriceCode(1197);
      Rental rental0 = new Rental(childrensMovie0, 1197);
      customer0.addRental(rental0);
      String string0 = customer0.statement();
      assertEquals("Rental Record for Rental Record for \n\tRental Record for Rental Record for \nYou owed 0.0\nYou earned 0 frequent renter points\n\t0.0\nYou owed 0.0\nYou earned 1 frequent renter points\n", string0);
  }

  //Test case number: 10
  /*
   * 76 covered goals:
   * Goal 1. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. nul.study.videostore.Customer.getName()Ljava/lang/String;: root-Branch
   * Goal 4. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true
   * Goal 5. nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false
   * Goal 6. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false
   * Goal 7. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false
   * Goal 8. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - true
   * Goal 9. nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false
   * Goal 10. nul.study.videostore.Customer.statement()Ljava/lang/String;: I98 Branch 7 IF_ICMPLE L41 - true
   * Goal 11. nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true
   * Goal 12. Branch nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.Customer:addRental(Lnul/study/videostore/Rental;)V
   * Goal 13. Branch nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.Customer:<init>(Ljava/lang/String;)V
   * Goal 14. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 15. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I32 Branch 1 IFEQ L25 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 16. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 2 TABLESWITCH L30 Case 0 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 17. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 5 TABLESWITCH L30 Default-Case - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 18. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 4 TABLESWITCH L30 Case 2 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 19. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I48 Branch 3 TABLESWITCH L30 Case 1 - false in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 20. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I98 Branch 7 IF_ICMPLE L41 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 21. Branch nul.study.videostore.Customer.statement()Ljava/lang/String;: I120 Branch 8 IF_ICMPNE L48 - true in context: nul.study.videostore.Customer:statement()Ljava/lang/String;
   * Goal 22. [Output]: nul.study.videostore.Customer.statement()Ljava/lang/String;:NonEmptyString
   * Goal 23. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 8
   * Goal 24. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 9
   * Goal 25. nul.study.videostore.Customer.<init>(Ljava/lang/String;)V: Line 63
   * Goal 26. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 12
   * Goal 27. nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V: Line 13
   * Goal 28. nul.study.videostore.Customer.getName()Ljava/lang/String;: Line 16
   * Goal 29. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 20
   * Goal 30. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 21
   * Goal 31. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 22
   * Goal 32. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 23
   * Goal 33. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 25
   * Goal 34. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 26
   * Goal 35. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 27
   * Goal 36. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 30
   * Goal 37. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 40
   * Goal 38. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 41
   * Goal 39. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 46
   * Goal 40. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 48
   * Goal 41. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 51
   * Goal 42. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 52
   * Goal 43. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 54
   * Goal 44. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 56
   * Goal 45. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 57
   * Goal 46. nul.study.videostore.Customer.statement()Ljava/lang/String;: Line 59
   * Goal 47. [METHOD] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 48. [METHOD] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 49. [METHOD] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 50. [METHODNOEX] nul.study.videostore.Customer.<init>(Ljava/lang/String;)V
   * Goal 51. [METHODNOEX] nul.study.videostore.Customer.addRental(Lnul/study/videostore/Rental;)V
   * Goal 52. [METHODNOEX] nul.study.videostore.Customer.statement()Ljava/lang/String;
   * Goal 53. Weak Mutation 0: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> 1.0
   * Goal 54. Weak Mutation 1: nul.study.videostore.Customer.statement()Ljava/lang/String;:20 - ReplaceConstant - 0.0 -> -1.0
   * Goal 55. Weak Mutation 2: nul.study.videostore.Customer.statement()Ljava/lang/String;:21 - ReplaceConstant - 0 -> 1
   * Goal 56. Weak Mutation 3: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - Rental Record for  -> 
   * Goal 57. Weak Mutation 4: nul.study.videostore.Customer.statement()Ljava/lang/String;:23 - ReplaceConstant - 
 -> 
   * Goal 58. Weak Mutation 5: nul.study.videostore.Customer.statement()Ljava/lang/String;:25 - ReplaceComparisonOperator == -> !=
   * Goal 59. Weak Mutation 6: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> 1.0
   * Goal 60. Weak Mutation 7: nul.study.videostore.Customer.statement()Ljava/lang/String;:26 - ReplaceConstant - 0.0 -> -1.0
   * Goal 61. Weak Mutation 64: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - InsertUnaryOp Negation of thisAmount
   * Goal 62. Weak Mutation 65: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 0.0
   * Goal 63. Weak Mutation 66: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 1.0
   * Goal 64. Weak Mutation 67: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> -1.0
   * Goal 65. Weak Mutation 68: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 0.5
   * Goal 66. Weak Mutation 69: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceConstant - 1.5 -> 2.5
   * Goal 67. Weak Mutation 70: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> %
   * Goal 68. Weak Mutation 71: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> -
   * Goal 69. Weak Mutation 72: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> *
   * Goal 70. Weak Mutation 73: nul.study.videostore.Customer.statement()Ljava/lang/String;:40 - ReplaceArithmeticOperator + -> /
   * Goal 71. Weak Mutation 74: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 0
   * Goal 72. Weak Mutation 75: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 1
   * Goal 73. Weak Mutation 76: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> -1
   * Goal 74. Weak Mutation 77: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 2
   * Goal 75. Weak Mutation 78: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceConstant - 3 -> 4
   * Goal 76. Weak Mutation 80: nul.study.videostore.Customer.statement()Ljava/lang/String;:41 - ReplaceComparisonOperator <= -> <
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Customer customer0 = new Customer("nul.study.videostore.Movie");
      ChildrensMovie childrensMovie0 = new ChildrensMovie("nul.study.videostore.Movie");
      Rental rental0 = new Rental(childrensMovie0, 3);
      customer0.addRental(rental0);
      String string0 = customer0.statement();
      assertEquals("Rental Record for nul.study.videostore.Movie\n\tnul.study.videostore.Movie\t1.5\nYou owed 1.5\nYou earned 1 frequent renter points\n", string0);
  }
}
