/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 30 17:47:35 GMT 2016
 */

package nul.study.videostore.EvoSuiteTests;

import org.junit.Test;
import static org.junit.Assert.*;
import nul.study.videostore.ChildrensMovie;
import nul.study.videostore.NewReleaseMovie;
import nul.study.videostore.RegularMovie;

public class Movie_ESTest {

  //Test case number: 0
  /*
   * 15 covered goals:
   * Goal 1. nul.study.videostore.Movie.getTitle()Ljava/lang/String;: root-Branch
   * Goal 2. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 3. Branch nul.study.videostore.Movie.getTitle()Ljava/lang/String;: root-Branch in context: nul.study.videostore.Movie:getTitle()Ljava/lang/String;
   * Goal 4. [Output]: nul.study.videostore.Movie.getTitle()Ljava/lang/String;:Null
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 6. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 7. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 8. nul.study.videostore.Movie.getTitle()Ljava/lang/String;: Line 26
   * Goal 9. [METHOD] nul.study.videostore.Movie.getTitle()Ljava/lang/String;
   * Goal 10. [METHODNOEX] nul.study.videostore.Movie.getTitle()Ljava/lang/String;
   * Goal 11. Weak Mutation 1: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> REGULAR
   * Goal 12. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 13. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 14. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 15. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewReleaseMovie newReleaseMovie0 = new NewReleaseMovie((String) null);
      newReleaseMovie0.getTitle();
      assertEquals(1, newReleaseMovie0.getPriceCode());
  }

  //Test case number: 1
  /*
   * 15 covered goals:
   * Goal 1. nul.study.videostore.Movie.getTitle()Ljava/lang/String;: root-Branch
   * Goal 2. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 3. Branch nul.study.videostore.Movie.getTitle()Ljava/lang/String;: root-Branch in context: nul.study.videostore.Movie:getTitle()Ljava/lang/String;
   * Goal 4. [Output]: nul.study.videostore.Movie.getTitle()Ljava/lang/String;:NonEmptyString
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 6. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 7. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 8. nul.study.videostore.Movie.getTitle()Ljava/lang/String;: Line 26
   * Goal 9. [METHOD] nul.study.videostore.Movie.getTitle()Ljava/lang/String;
   * Goal 10. [METHODNOEX] nul.study.videostore.Movie.getTitle()Ljava/lang/String;
   * Goal 11. Weak Mutation 0: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 12. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 13. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 14. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 15. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegularMovie regularMovie0 = new RegularMovie("$}[x");
      regularMovie0.getTitle();
      assertEquals(0, regularMovie0.getPriceCode());
  }

  //Test case number: 2
  /*
   * 20 covered goals:
   * Goal 1. nul.study.videostore.Movie.getPriceCode()I: root-Branch
   * Goal 2. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 3. Branch nul.study.videostore.Movie.getPriceCode()I: root-Branch in context: nul.study.videostore.Movie:getPriceCode()I
   * Goal 4. [Output]: nul.study.videostore.Movie.getPriceCode()I:Positive
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 6. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 7. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 8. nul.study.videostore.Movie.getPriceCode()I: Line 18
   * Goal 9. [METHOD] nul.study.videostore.Movie.getPriceCode()I
   * Goal 10. [METHODNOEX] nul.study.videostore.Movie.getPriceCode()I
   * Goal 11. Weak Mutation 1: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> REGULAR
   * Goal 12. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 13. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 14. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 15. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   * Goal 16. Weak Mutation 7: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> REGULAR
   * Goal 17. Weak Mutation 8: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 18. Weak Mutation 9: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp Negation
   * Goal 19. Weak Mutation 10: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp +1
   * Goal 20. Weak Mutation 11: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp -1
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NewReleaseMovie newReleaseMovie0 = new NewReleaseMovie("T!RsM5VsE~o<]->N");
      int int0 = newReleaseMovie0.getPriceCode();
      assertEquals(1, int0);
  }

  //Test case number: 3
  /*
   * 12 covered goals:
   * Goal 1. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 2. [Output]: nul.study.videostore.Movie.determineFrequentRenterPoints(I)I:Positive
   * Goal 3. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 4. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 6. [METHOD] nul.study.videostore.Movie.determineFrequentRenterPoints(I)I
   * Goal 7. [METHODNOEX] nul.study.videostore.Movie.determineFrequentRenterPoints(I)I
   * Goal 8. Weak Mutation 0: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 9. Weak Mutation 1: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> REGULAR
   * Goal 10. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 11. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 12. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChildrensMovie childrensMovie0 = new ChildrensMovie("");
      childrensMovie0.determineFrequentRenterPoints((-249));
      assertEquals(2, childrensMovie0.getPriceCode());
  }

  //Test case number: 4
  /*
   * 12 covered goals:
   * Goal 1. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 2. [Output]: nul.study.videostore.Movie.determineAmount(I)D:Zero
   * Goal 3. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 4. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 6. [METHOD] nul.study.videostore.Movie.determineAmount(I)D
   * Goal 7. [METHODNOEX] nul.study.videostore.Movie.determineAmount(I)D
   * Goal 8. Weak Mutation 1: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> REGULAR
   * Goal 9. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 10. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 11. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 12. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NewReleaseMovie newReleaseMovie0 = new NewReleaseMovie((String) null);
      newReleaseMovie0.determineAmount(0);
      assertEquals(1, newReleaseMovie0.getPriceCode());
  }

  //Test case number: 5
  /*
   * 12 covered goals:
   * Goal 1. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 2. [Output]: nul.study.videostore.Movie.determineAmount(I)D:Positive
   * Goal 3. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 4. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 6. [METHOD] nul.study.videostore.Movie.determineAmount(I)D
   * Goal 7. [METHODNOEX] nul.study.videostore.Movie.determineAmount(I)D
   * Goal 8. Weak Mutation 0: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 9. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 10. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 11. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 12. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RegularMovie regularMovie0 = new RegularMovie("");
      regularMovie0.determineAmount((-1038));
      assertEquals(0, regularMovie0.getPriceCode());
  }

  //Test case number: 6
  /*
   * 12 covered goals:
   * Goal 1. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 2. [Output]: nul.study.videostore.Movie.determineAmount(I)D:Negative
   * Goal 3. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 4. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 6. [METHOD] nul.study.videostore.Movie.determineAmount(I)D
   * Goal 7. [METHODNOEX] nul.study.videostore.Movie.determineAmount(I)D
   * Goal 8. Weak Mutation 1: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> REGULAR
   * Goal 9. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 10. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 11. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 12. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      NewReleaseMovie newReleaseMovie0 = new NewReleaseMovie("nul.study.videostore.Movie");
      newReleaseMovie0.determineAmount((-987));
      assertEquals(1, newReleaseMovie0.getPriceCode());
  }

  //Test case number: 7
  /*
   * 33 covered goals:
   * Goal 1. nul.study.videostore.Movie.getPriceCode()I: root-Branch
   * Goal 2. nul.study.videostore.Movie.setPriceCode(I)V: root-Branch
   * Goal 3. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 4. Branch nul.study.videostore.Movie.setPriceCode(I)V: root-Branch in context: nul.study.videostore.Movie:setPriceCode(I)V
   * Goal 5. Branch nul.study.videostore.Movie.getPriceCode()I: root-Branch in context: nul.study.videostore.Movie:getPriceCode()I
   * Goal 6. [Output]: nul.study.videostore.Movie.getPriceCode()I:Negative
   * Goal 7. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 8. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 9. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 10. nul.study.videostore.Movie.getPriceCode()I: Line 18
   * Goal 11. nul.study.videostore.Movie.setPriceCode(I)V: Line 22
   * Goal 12. nul.study.videostore.Movie.setPriceCode(I)V: Line 23
   * Goal 13. [METHOD] nul.study.videostore.Movie.getPriceCode()I
   * Goal 14. [METHOD] nul.study.videostore.Movie.setPriceCode(I)V
   * Goal 15. [METHODNOEX] nul.study.videostore.Movie.getPriceCode()I
   * Goal 16. [METHODNOEX] nul.study.videostore.Movie.setPriceCode(I)V
   * Goal 17. Weak Mutation 0: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 18. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 19. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 20. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 21. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   * Goal 22. Weak Mutation 6: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 23. Weak Mutation 7: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> REGULAR
   * Goal 24. Weak Mutation 8: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 25. Weak Mutation 9: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp Negation
   * Goal 26. Weak Mutation 10: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp +1
   * Goal 27. Weak Mutation 11: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp -1
   * Goal 28. Weak Mutation 12: nul.study.videostore.Movie.setPriceCode(I)V:22 - ReplaceVariable code -> NEW_RELEASE
   * Goal 29. Weak Mutation 13: nul.study.videostore.Movie.setPriceCode(I)V:22 - ReplaceVariable code -> REGULAR
   * Goal 30. Weak Mutation 14: nul.study.videostore.Movie.setPriceCode(I)V:22 - ReplaceVariable code -> CHILDRENS
   * Goal 31. Weak Mutation 15: nul.study.videostore.Movie.setPriceCode(I)V:22 - InsertUnaryOp Negation of code
   * Goal 32. Weak Mutation 16: nul.study.videostore.Movie.setPriceCode(I)V:22 - InsertUnaryOp IINC 1 code
   * Goal 33. Weak Mutation 17: nul.study.videostore.Movie.setPriceCode(I)V:22 - InsertUnaryOp IINC -1 code
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RegularMovie regularMovie0 = new RegularMovie(".1");
      regularMovie0.setPriceCode((-249));
      int int0 = regularMovie0.getPriceCode();
      assertEquals((-249), int0);
  }

  //Test case number: 8
  /*
   * 15 covered goals:
   * Goal 1. nul.study.videostore.Movie.getTitle()Ljava/lang/String;: root-Branch
   * Goal 2. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 3. Branch nul.study.videostore.Movie.getTitle()Ljava/lang/String;: root-Branch in context: nul.study.videostore.Movie:getTitle()Ljava/lang/String;
   * Goal 4. [Output]: nul.study.videostore.Movie.getTitle()Ljava/lang/String;:EmptyString
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 6. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 7. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 8. nul.study.videostore.Movie.getTitle()Ljava/lang/String;: Line 26
   * Goal 9. [METHOD] nul.study.videostore.Movie.getTitle()Ljava/lang/String;
   * Goal 10. [METHODNOEX] nul.study.videostore.Movie.getTitle()Ljava/lang/String;
   * Goal 11. Weak Mutation 0: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 12. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 13. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 14. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 15. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      RegularMovie regularMovie0 = new RegularMovie("");
      regularMovie0.getTitle();
      assertEquals(0, regularMovie0.getPriceCode());
  }

  //Test case number: 9
  /*
   * 20 covered goals:
   * Goal 1. nul.study.videostore.Movie.getPriceCode()I: root-Branch
   * Goal 2. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: root-Branch
   * Goal 3. Branch nul.study.videostore.Movie.getPriceCode()I: root-Branch in context: nul.study.videostore.Movie:getPriceCode()I
   * Goal 4. [Output]: nul.study.videostore.Movie.getPriceCode()I:Zero
   * Goal 5. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 13
   * Goal 6. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 14
   * Goal 7. nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V: Line 15
   * Goal 8. nul.study.videostore.Movie.getPriceCode()I: Line 18
   * Goal 9. [METHOD] nul.study.videostore.Movie.getPriceCode()I
   * Goal 10. [METHODNOEX] nul.study.videostore.Movie.getPriceCode()I
   * Goal 11. Weak Mutation 0: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 12. Weak Mutation 2: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 13. Weak Mutation 3: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp Negation of priceCode
   * Goal 14. Weak Mutation 4: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC 1 priceCode
   * Goal 15. Weak Mutation 5: nul.study.videostore.Movie.<init>(Ljava/lang/String;I)V:14 - InsertUnaryOp IINC -1 priceCode
   * Goal 16. Weak Mutation 6: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> NEW_RELEASE
   * Goal 17. Weak Mutation 8: nul.study.videostore.Movie.getPriceCode()I:18 - ReplaceVariable priceCode -> CHILDRENS
   * Goal 18. Weak Mutation 9: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp Negation
   * Goal 19. Weak Mutation 10: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp +1
   * Goal 20. Weak Mutation 11: nul.study.videostore.Movie.getPriceCode()I:18 - InsertUnaryOp -1
   */

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      RegularMovie regularMovie0 = new RegularMovie(".1");
      int int0 = regularMovie0.getPriceCode();
      assertEquals(0, int0);
  }
}
