/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 30 17:52:28 GMT 2016
 */

package nul.study.videostore.EvoSuiteTests;

import org.junit.Test;
import static org.junit.Assert.*;
import nul.study.videostore.Movie;
import nul.study.videostore.Rental;
import nul.study.videostore.RentalStatement;
public class RentalStatement_ESTest {

  //Test case number: 0
  /*
   * 14 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: root-Branch
   * Goal 3. Branch nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: root-Branch in context: nul.study.videostore.RentalStatement:getName()Ljava/lang/String;
   * Goal 4. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 5. [Output]: nul.study.videostore.RentalStatement.getName()Ljava/lang/String;:Null
   * Goal 6. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 7. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 8. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 9. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 10. nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: Line 31
   * Goal 11. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 12. [METHOD] nul.study.videostore.RentalStatement.getName()Ljava/lang/String;
   * Goal 13. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] nul.study.videostore.RentalStatement.getName()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement((String) null);
      String string0 = rentalStatement0.getName();
      assertNull(string0);
  }

  //Test case number: 1
  /*
   * 14 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: root-Branch
   * Goal 3. Branch nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: root-Branch in context: nul.study.videostore.RentalStatement:getName()Ljava/lang/String;
   * Goal 4. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 5. [Output]: nul.study.videostore.RentalStatement.getName()Ljava/lang/String;:NonEmptyString
   * Goal 6. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 7. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 8. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 9. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 10. nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: Line 31
   * Goal 11. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 12. [METHOD] nul.study.videostore.RentalStatement.getName()Ljava/lang/String;
   * Goal 13. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] nul.study.videostore.RentalStatement.getName()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement(" frequent renter points\n");
      String string0 = rentalStatement0.getName();
      assertEquals(" frequent renter points\n", string0);
  }

  //Test case number: 2
  /*
   * 14 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: root-Branch
   * Goal 3. Branch nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: root-Branch in context: nul.study.videostore.RentalStatement:getName()Ljava/lang/String;
   * Goal 4. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 5. [Output]: nul.study.videostore.RentalStatement.getName()Ljava/lang/String;:EmptyString
   * Goal 6. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 7. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 8. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 9. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 10. nul.study.videostore.RentalStatement.getName()Ljava/lang/String;: Line 31
   * Goal 11. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 12. [METHOD] nul.study.videostore.RentalStatement.getName()Ljava/lang/String;
   * Goal 13. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] nul.study.videostore.RentalStatement.getName()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement("");
      String string0 = rentalStatement0.getName();
      assertEquals("", string0);
  }

  //Test case number: 3
  /*
   * 15 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.getAmountOwed()D: root-Branch
   * Goal 3. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 4. Branch nul.study.videostore.RentalStatement.getAmountOwed()D: root-Branch in context: nul.study.videostore.RentalStatement:getAmountOwed()D
   * Goal 5. [Output]: nul.study.videostore.RentalStatement.getAmountOwed()D:Zero
   * Goal 6. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 7. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 8. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 9. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 10. nul.study.videostore.RentalStatement.getAmountOwed()D: Line 32
   * Goal 11. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 12. [METHOD] nul.study.videostore.RentalStatement.getAmountOwed()D
   * Goal 13. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] nul.study.videostore.RentalStatement.getAmountOwed()D
   * Goal 15. Weak Mutation 32: nul.study.videostore.RentalStatement.getAmountOwed()D:32 - InsertUnaryOp Negation
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement("nhFJ_PD.");
      double double0 = rentalStatement0.getAmountOwed();
      assertEquals(0.0, double0, 0.01);
  }

  //Test case number: 4
  /*
   * 14 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: root-Branch
   * Goal 3. Branch nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: root-Branch in context: nul.study.videostore.RentalStatement:addRental(Lnul/study/videostore/Rental;)V
   * Goal 4. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 5. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 6. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 7. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 8. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 9. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 18
   * Goal 10. nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;: Line 18
   * Goal 11. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 12. [METHOD] nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V
   * Goal 13. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement("nhFJ_PD.");
      Rental rental0 = new Rental((Movie) null, 0);
      rentalStatement0.addRental(rental0);
      assertEquals(0.0, rentalStatement0.getAmountOwed(), 0.01);
  }

  //Test case number: 5
  /*
   * 25 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.clearTotals()V: root-Branch
   * Goal 3. nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;: root-Branch
   * Goal 4. Branch nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;: root-Branch in context: nul.study.videostore.RentalStatement:makeRentalStatement()Ljava/lang/String;
   * Goal 5. Branch nul.study.videostore.RentalStatement.clearTotals()V: root-Branch in context: 
   * Goal 6. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 7. [Output]: nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;:Null
   * Goal 8. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 9. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 10. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 11. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 12. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 18
   * Goal 13. nul.study.videostore.RentalStatement.clearTotals()V: Line 19
   * Goal 14. nul.study.videostore.RentalStatement.clearTotals()V: Line 20
   * Goal 15. nul.study.videostore.RentalStatement.clearTotals()V: Line 21
   * Goal 16. nul.study.videostore.RentalStatement.makeHeader()Ljava/lang/String;: Line 21
   * Goal 17. nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;: Line 18
   * Goal 18. nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;: Line 19
   * Goal 19. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 20. [METHOD] nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;
   * Goal 21. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 22. [METHODNOEX] nul.study.videostore.RentalStatement.makeRentalStatement()Ljava/lang/String;
   * Goal 23. Weak Mutation 0: nul.study.videostore.RentalStatement.clearTotals()V:19 - ReplaceConstant - 0.0 -> 1.0
   * Goal 24. Weak Mutation 1: nul.study.videostore.RentalStatement.clearTotals()V:19 - ReplaceConstant - 0.0 -> -1.0
   * Goal 25. Weak Mutation 2: nul.study.videostore.RentalStatement.clearTotals()V:20 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement((String) null);
      rentalStatement0.makeRentalStatement();
      assertEquals(0, rentalStatement0.getFrequentRenterPoints());
      assertEquals(0.0, rentalStatement0.getAmountOwed(), 0.01);
  }

  //Test case number: 6
  /*
   * 17 covered goals:
   * Goal 1. nul.study.videostore.RentalStatement.getFrequentRenterPoints()I: root-Branch
   * Goal 2. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 3. Branch nul.study.videostore.RentalStatement.getFrequentRenterPoints()I: root-Branch in context: nul.study.videostore.RentalStatement:getFrequentRenterPoints()I
   * Goal 4. Branch nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: root-Branch in context: nul.study.videostore.RentalStatement:<init>(Ljava/lang/String;)V
   * Goal 5. [Output]: nul.study.videostore.RentalStatement.getFrequentRenterPoints()I:Zero
   * Goal 6. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 13
   * Goal 7. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 16
   * Goal 8. nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V: Line 17
   * Goal 9. nul.study.videostore.RentalStatement.addRental(Lnul/study/videostore/Rental;)V: Line 17
   * Goal 10. nul.study.videostore.RentalStatement.getFrequentRenterPoints()I: Line 33
   * Goal 11. [METHOD] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 12. [METHOD] nul.study.videostore.RentalStatement.getFrequentRenterPoints()I
   * Goal 13. [METHODNOEX] nul.study.videostore.RentalStatement.<init>(Ljava/lang/String;)V
   * Goal 14. [METHODNOEX] nul.study.videostore.RentalStatement.getFrequentRenterPoints()I
   * Goal 15. Weak Mutation 33: nul.study.videostore.RentalStatement.getFrequentRenterPoints()I:33 - InsertUnaryOp Negation
   * Goal 16. Weak Mutation 34: nul.study.videostore.RentalStatement.getFrequentRenterPoints()I:33 - InsertUnaryOp +1
   * Goal 17. Weak Mutation 35: nul.study.videostore.RentalStatement.getFrequentRenterPoints()I:33 - InsertUnaryOp -1
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RentalStatement rentalStatement0 = new RentalStatement("nhFJ_PD.");
      int int0 = rentalStatement0.getFrequentRenterPoints();
      assertEquals(0, int0);
  }
}
